version: "3.7"

services:
  ss-server:
    container_name: ss
    image: laucyun/shadowsocks-go:1.2.1
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    volumes:
      - ./ss-config.json:/opt/shadowsocks/ss-config.json
    command: [
        "-c",
        "/opt/shadowsocks/ss-config.json"
    ]
    restart: always