version: "3.8"

services:
  ss-server:
    container_name: ${SS_CONTAINER_NAME}
    image: acrisliu/shadowsocks-libev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}/tcp"
    env_file:
      - .ss_server.env
    restart: on-failure
